site_name: Jitsi

repo_name: "2023.2-Jitsi"
repo_url: "https://github.com/Requisitos-de-Software/2023.2-Jitsi.git"

theme:
  name: material
  logo: assets/logoJitsi.png
  favicon: assets/favicon.png
  language: "pt"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Tema escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Tema claro
  features:
    - navigation.tabs
  font:
    text: "Calibri"
    code: "sans-serif"

nav:
  - Início: index.md
  - Atas de Reunião: 
    - Reunião 01: atas/reuniao-01.md