site_name: Jitsi

repo_name: "2023.2-Jitsi"
repo_url: "https://github.com/Requisitos-de-Software/2023.2-Jitsi.git"

theme:
  name: material
  logo: assets/logoJitsi.png
  favicon: assets/favicon.png
  language: "pt"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      toggle:
        icon: material/weather-sunny
        name: Tema escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/weather-night
        name: Tema claro
  features:
    - navigation.tabs
  font:
    text: "Calibri"
    code: "sans-serif"

nav:
  - Início: index.md
  - Atas de Reunião: 
    - Reunião 01: atas/reuniao-01.md
    - Reunião 02: atas/reuniao-02.md
  - Planejamento:
    - Cronograma: Planejamento/cronograma.md 
    - Cronograma Realizado: Planejamento/cronograma_realizado.md
    - Ferramentas: Planejamento/ferramentas.md
    - Heatmap: Planejamento/heatmap.md
    - Metodologias: Planejamento/metodologias.md
  - Pré-Rastreabilidade:
    - Escolha do Aplicativo: PreRastreabilidade/AppEscolhido.md  
    - Rich Picture: PreRastreabilidade/RichPicture.md
  - Apresentações: 
    - Etapa 01: apresentacoes/etapa-01.md
    