site_name: Jitsi

repo_name: "2023.2-Jitsi"
repo_url: "https://github.com/Requisitos-de-Software/2023.2-Jitsi.git"

theme:
  name: material
  logo: assets/logoJitsi.png
  favicon: assets/favicon.png
  language: "pt"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      toggle:
        icon: material/weather-sunny
        name: Tema escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/weather-night
        name: Tema claro
  features:
    - navigation.tabs
  font:
    text: "Calibri"
    code: "sans-serif"

nav:
  - Início: index.md
  - Atas de Reunião: 
    - Reunião 01: Atas/reuniao-01.md
    - Reunião 02: Atas/reuniao-02.md
  - Planejamento:
    - Cronograma: Planejamento/cronograma.md 
    - Cronograma Realizado: Planejamento/cronograma_realizado.md
    - Ferramentas: Planejamento/ferramentas.md
    - Heatmap: Planejamento/heatmap.md
    - Metodologias: Planejamento/metodologias.md
  - Elicitação:
    - Perfil do Usuário:  
      - Personas: Elicitação/perfilDoUsuario/personas.md  
      - Questionário: Elicitação/perfilDoUsuario/questionario.md
    - Técnicas:
      - Introspecção: Elicitação/tecnicas/introspecção.md
      - Brainstorming: Elicitação/tecnicas/brainstorming.md
      - Entrevista: Elicitação/tecnicas/entrevista.md
    - Priorização: 
      - 100 doláres: Elicitação/priorizacao/100Dolares.md
      - MoSCoW: Elicitação/priorizacao/MoSCoW.md
  - Pré-Rastreabilidade:
    - Escolha do Aplicativo: PreRastreabilidade/AppEscolhido.md  
    - Rich Picture: PreRastreabilidade/RichPicture.md
  - Apresentações: 
    - Etapa 01: Apresentacoes/etapa-01.md
    