site_name: Jitsi

repo_name: "2023.2-Jitsi"
repo_url: "https://github.com/Requisitos-de-Software/2023.2-Jitsi.git"

theme:
  name: material
  logo: assets/logoJitsi.png
  favicon: assets/favicon.png
  language: "pt"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      toggle:
        icon: material/weather-sunny
        name: Tema escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/weather-night
        name: Tema claro
  features:
    - navigation.tabs
  font:
    text: "Calibri"
    code: "sans-serif"

nav:
  - Início: index.md
  - Atas de Reunião: 
    - Reunião 01: atas/reuniao-01.md
    - Reunião 02: atas/reuniao-02.md
    - Reunião 03: atas/reuniao-03.md
    - Reunião 04: atas/reuniao-04.md
  - Planejamento:
    - Cronograma: Planejamento/cronograma.md 
    - Cronograma Realizado: Planejamento/cronograma_realizado.md
    - Ferramentas: Planejamento/ferramentas.md
    - Heatmap: Planejamento/heatmap.md
    - Metodologias: Planejamento/metodologias.md
  - Elicitação:
    - Planejamento: Elicitacao/planejamento.md
    - Perfil do Usuário:
      - Personas: Elicitacao/perfilDoUsuario/personas.md  
      - Questionário: Elicitacao/perfilDoUsuario/questionario.md
    - Técnicas:
      - Brainstorming: Elicitacao/tecnicas/brainstorming.md
      - Entrevista: Elicitacao/tecnicas/entrevista.md
      - Introspecção: Elicitacao/tecnicas/introspecção.md
      - Observação: Elicitacao/tecnicas/observacao.md
    - Priorização: 
      - First Things First : Elicitacao/priorizacao/ftf.md
      - MoSCoW: Elicitacao/priorizacao/MoSCoW.md
      - Three Level Scale:  Elicitacao/priorizacao/TLS.md
    - Requisitos Elicitados: Elicitacao/requisitos-elicitados.md
  - Modelagem:
      - Cenários: Modelagem/cenarios.md
      - Léxicos: Modelagem/lexico.md
      - Casos de Uso: Modelagem/casosDeUso.md
      - Especificação Suplementar: Modelagem/especificacaoSuplementar.md
      - Agil:
        - Backlog: Modelagem/Agil/backlog.md
        - Histórias de usuário: Modelagem/Agil/historias.md
        - NFR Framework: Modelagem/Agil/nfr-framework.md
  - Verificação:
    - Grupo +1:
      - Entrega 01: 
        - Cronograma: Verificacao/Grupo+1/Entrega_1/Cronograma.md
        - Ferramentas: Verificacao/Grupo+1/Entrega_1/Ferramentas.md
        - Planejamento: Verificacao/Grupo+1/Entrega_1/Planejamento.md
        - Rich Picture: Verificacao/Grupo+1/Entrega_1/RichPicture.md
      - Entrega 02: 
        - Planejamento: Verificacao/Grupo+1/Entrega_2/Planejamento.md
        - Elicitação: Verificacao/Grupo+1/Entrega_2/Elicitacao.md
        - Priorização: 
          - First Things First: Verificacao/Grupo+1/Entrega_2/Ftf.md
          - Moscow:  Verificacao/Grupo+1/Entrega_2/Moscow.md
          - Three-Level Scale:  Verificacao/Grupo+1/Entrega_2/Tls.md
      - Entrega 03: 
        - Planejamento: Verificacao/Grupo+1/Entrega_3/Planejamento.md
        - Casos de Uso: Verificacao/Grupo+1/Entrega_3/CasosDeUso.md
        - Lexicos: Verificacao/Grupo+1/Entrega_3/Lexicos.md
        - Especificação Suplementar: Verificacao/Grupo+1/Entrega_3/EspecificacaoS.md
        - Cenários: Verificacao/Grupo+1/Entrega_3/Cenarios.md
      - Entrega 04:  
        - Planejamento: Verificacao/Grupo+1/Entrega_4/Planejamento.md
        - NFR: Verificacao/Grupo+1/Entrega_4/NFR.md
        - Backlog: Verificacao/Grupo+1/Entrega_4/Backlog.md
        - Histórias de Usuário: Verificacao/Grupo+1/Entrega_4/HistoriaDeUsuario.md
    - Grupo:
      - Entrega 01:
        - Cronograma: Verificacao/Grupo/Entrega_1/Cronograma.md
        - Ferramentas: Verificacao/Grupo/Entrega_1/Ferramentas.md
        - Metódologias: Verificacao/Grupo/Entrega_1/Metodologias.md
      - Entrega 02:
        - Moscow: Verificacao/Grupo/Entrega_2/Moscow.md
        - Entrevista: Verificacao/Grupo/Entrega_2/Entrevista.md
      - Entrega 03: 
        - Cenários: Verificacao/Grupo/Entrega_3/Cenarios.md
      - Entrega 04: 
        - História de Usuário: Verificacao/Grupo/Entrega_4/HistoriaDeUsuario.md
  - Pré-Rastreabilidade:
    - Escolha do Aplicativo: PreRastreabilidade/AppEscolhido.md  
    - Rich Picture: PreRastreabilidade/RichPicture.md
  - Pós-Rastreabilidade:
    - Backward-From: PosRastreabilidade/Backward-From.md
    - Forward-From: PosRastreabilidade/Forward_from.md
    - Matriz de Rastreabilidade: PosRastreabilidade/matrizRastreabilidade.md
  - Apresentações: 
    - Etapa 01: apresentacoes/etapa-01.md
    - Etapa 02: apresentacoes/etapa-02.md
    - Etapa 03: apresentacoes/etapa-03.md
    - Etapa 04: apresentacoes/etapa-04.md
    - Etapa 05: apresentacoes/etapa-05.md
    - Etapa 06: apresentacoes/etapa-06.md
    